ENERGIA_COMIDA_LOBOS = 20
ENERGIA_COMIDA_OVEJAS = 4
ENERGIA_PERDIDA_STEP = 1
ENERGIA_PERDIDA_REPRODUCCION = 2 # a la mitad

PROB_REPRODUCCION_LOBO = 0.05 # 5%
PROB_REPRODUCCION_OVEJA = 0.04 # 4%
CONTADOR_CRECIMIENTO_INICIAL = 30
STATUS_PASTO_INICIAL = True

NUM_LOBOS_INICIAL = 50
NUM_OVEJAS_INICIAL = 100
WIDTH_GRID = 50
HEIGHT_GRID = 50